import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import styles from "./layout.module.scss";
import { Header } from "@/components/Header/Header";
import { SideMenu } from "@/components/SideMenu/SideMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.container}>
          <Header />
          <div className={styles.contentWrapper}>
            <SideMenu />
            <main className={styles.main}>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
